name: Trigger auto deployment for capps-backend-5jrdux235oi5k

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/capps-backend-5jrdux235oi5k-AutoDeployTrigger-61319073-1c89-4a1f-aa85-7003901874ac.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CAPPSBACKEND5JRDUX235OI5K_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: aoaiaudiorag03acr5jrdux235oi5k.azurecr.io
          registryUsername: ${{ secrets.CAPPSBACKEND5JRDUX235OI5K_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAPPSBACKEND5JRDUX235OI5K_REGISTRY_PASSWORD }}
          containerAppName: capps-backend-5jrdux235oi5k
          resourceGroup: rg-aoai-audio-rag03
          imageToBuild: aoaiaudiorag03acr5jrdux235oi5k.azurecr.io/aisearch-openai-rag-audio/backend-aoai-audio-rag03:${{ github.sha }}
          
            

     

